INSERT INTO
    group_keywords (
        group_master_id,
        keyword,
        normalized_keyword,
        weight,
        match_type,
        active
    )
VALUES
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'summer'
        ),
        '夏',
        '夏',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'summer'
        ),
        '暑さ',
        '夏',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'summer'
        ),
        '猛暑',
        '夏',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'summer'
        ),
        '花火',
        '夏',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'summer'
        ),
        '海',
        '夏',
        0.70,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'cooking'
        ),
        '料理',
        '料理',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'cooking'
        ),
        'ごはん',
        '料理',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'cooking'
        ),
        '自炊',
        '料理',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'cooking'
        ),
        'レシピ',
        '料理',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'cooking'
        ),
        '弁当',
        '料理',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'drawing'
        ),
        '絵',
        '絵',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'drawing'
        ),
        'イラスト',
        '絵',
        0.95,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'drawing'
        ),
        '落書き',
        '絵',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'drawing'
        ),
        'スケッチ',
        '絵',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'drawing'
        ),
        '絵描き',
        '絵',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'video'
        ),
        '動画',
        '動画',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'video'
        ),
        '映画',
        '動画',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'video'
        ),
        'アニメ',
        '動画',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'video'
        ),
        'YouTube',
        '動画',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'video'
        ),
        '視聴',
        '動画',
        0.70,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'cleaning'
        ),
        '掃除',
        '掃除',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'cleaning'
        ),
        '片付け',
        '掃除',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'cleaning'
        ),
        '洗濯',
        '掃除',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'cleaning'
        ),
        '整理',
        '掃除',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'cleaning'
        ),
        '家事',
        '掃除',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'app'
        ),
        'アプリ',
        'アプリ',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'app'
        ),
        'スマホアプリ',
        'アプリ',
        0.95,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'app'
        ),
        'Webアプリ',
        'アプリ',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'app'
        ),
        'サービス',
        'アプリ',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'app'
        ),
        '開発',
        'アプリ',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'streaming'
        ),
        '配信',
        '配信',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'streaming'
        ),
        'ライブ配信',
        '配信',
        0.95,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'streaming'
        ),
        '生放送',
        '配信',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'streaming'
        ),
        '実況',
        '配信',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'streaming'
        ),
        '配信者',
        '配信',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'study'
        ),
        '勉強',
        '勉強',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'study'
        ),
        '学習',
        '勉強',
        0.95,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'study'
        ),
        '宿題',
        '勉強',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'study'
        ),
        '課題',
        '勉強',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'study'
        ),
        '復習',
        '勉強',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'coworker'
        ),
        '同僚',
        '同僚',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'coworker'
        ),
        '職場',
        '同僚',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'coworker'
        ),
        '先輩',
        '同僚',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'coworker'
        ),
        '後輩',
        '同僚',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'coworker'
        ),
        'チーム',
        '同僚',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'partner'
        ),
        '恋人',
        '恋人',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'partner'
        ),
        '彼氏',
        '恋人',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'partner'
        ),
        '彼女',
        '恋人',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'partner'
        ),
        'パートナー',
        '恋人',
        0.95,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'partner'
        ),
        'デート',
        '恋人',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'birthday'
        ),
        '誕生日',
        '誕生日',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'birthday'
        ),
        'バースデー',
        '誕生日',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'birthday'
        ),
        'プレゼント',
        '誕生日',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'birthday'
        ),
        'ケーキ',
        '誕生日',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'birthday'
        ),
        'お祝い',
        '誕生日',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'holiday'
        ),
        '休日',
        '休日',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'holiday'
        ),
        '休み',
        '休日',
        0.95,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'holiday'
        ),
        '連休',
        '休日',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'holiday'
        ),
        '週末',
        '休日',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'holiday'
        ),
        '暇',
        '休日',
        0.60,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'idea'
        ),
        'アイデア',
        'アイデア',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'idea'
        ),
        '発想',
        'アイデア',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'idea'
        ),
        'ひらめき',
        'アイデア',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'idea'
        ),
        '企画',
        'アイデア',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'idea'
        ),
        'ネタ',
        'アイデア',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'school'
        ),
        '学校',
        '学校',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'school'
        ),
        '大学',
        '学校',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'school'
        ),
        '授業',
        '学校',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'school'
        ),
        '教室',
        '学校',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'school'
        ),
        '先生',
        '学校',
        0.70,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'sleepiness'
        ),
        '眠気',
        '眠気',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'sleepiness'
        ),
        '眠い',
        '眠気',
        0.95,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'sleepiness'
        ),
        '寝不足',
        '眠気',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'sleepiness'
        ),
        'あくび',
        '眠気',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'sleepiness'
        ),
        'ウトウト',
        '眠気',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'travel'
        ),
        '旅行',
        '旅行',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'travel'
        ),
        '旅',
        '旅行',
        0.95,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'travel'
        ),
        '観光',
        '旅行',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'travel'
        ),
        'ホテル',
        '旅行',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'travel'
        ),
        '新幹線',
        '旅行',
        0.70,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'exam'
        ),
        '試験',
        '試験',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'exam'
        ),
        'テスト',
        '試験',
        0.95,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'exam'
        ),
        '受験',
        '試験',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'exam'
        ),
        '模試',
        '試験',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'exam'
        ),
        '資格',
        '試験',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'mountain'
        ),
        '山',
        '山',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'mountain'
        ),
        '登山',
        '山',
        0.95,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'mountain'
        ),
        'ハイキング',
        '山',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'mountain'
        ),
        'キャンプ',
        '山',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'mountain'
        ),
        '自然',
        '山',
        0.70,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'notification'
        ),
        '通知',
        '通知',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'notification'
        ),
        'メッセージ',
        '通知',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'notification'
        ),
        'アラート',
        '通知',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'notification'
        ),
        'メール',
        '通知',
        0.70,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'notification'
        ),
        'リマインダー',
        '通知',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'photo'
        ),
        '写真',
        '写真',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'photo'
        ),
        'カメラ',
        '写真',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'photo'
        ),
        '撮影',
        '写真',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'photo'
        ),
        'アルバム',
        '写真',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'photo'
        ),
        '画像',
        '写真',
        0.70,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'festival'
        ),
        '祭り',
        '祭り',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'festival'
        ),
        'お祭り',
        '祭り',
        0.95,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'festival'
        ),
        'フェス',
        '祭り',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'festival'
        ),
        '屋台',
        '祭り',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'festival'
        ),
        'イベント',
        '祭り',
        0.65,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'life'
        ),
        '人生',
        '人生',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'life'
        ),
        '生活',
        '人生',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'life'
        ),
        '将来',
        '人生',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'life'
        ),
        '日常',
        '人生',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'life'
        ),
        '気持ち',
        '人生',
        0.65,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'exercise'
        ),
        '運動',
        '運動',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'exercise'
        ),
        '筋トレ',
        '運動',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'exercise'
        ),
        'ランニング',
        '運動',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'exercise'
        ),
        '散歩',
        '運動',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'exercise'
        ),
        'ジム',
        '運動',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'handmade'
        ),
        'ハンドメイド',
        'ハンドメイド',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'handmade'
        ),
        '手作り',
        'ハンドメイド',
        0.95,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'handmade'
        ),
        '編み物',
        'ハンドメイド',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'handmade'
        ),
        '工作',
        'ハンドメイド',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'handmade'
        ),
        'アクセサリー',
        'ハンドメイド',
        0.70,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'child'
        ),
        '子ども',
        '子ども',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'child'
        ),
        '子供',
        '子ども',
        0.95,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'child'
        ),
        '育児',
        '子ども',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'child'
        ),
        '赤ちゃん',
        '子ども',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'child'
        ),
        '家族',
        '子ども',
        0.70,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'gadget'
        ),
        'ガジェット',
        'ガジェット',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'gadget'
        ),
        'スマホ',
        'ガジェット',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'gadget'
        ),
        'PC',
        'ガジェット',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'gadget'
        ),
        'パソコン',
        'ガジェット',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'gadget'
        ),
        'キーボード',
        'ガジェット',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'home'
        ),
        '家',
        '家',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'home'
        ),
        '部屋',
        '家',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'home'
        ),
        '自宅',
        '家',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'home'
        ),
        'リビング',
        '家',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'home'
        ),
        '寝室',
        '家',
        0.70,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'sleep'
        ),
        '睡眠',
        '睡眠',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'sleep'
        ),
        '寝る',
        '睡眠',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'sleep'
        ),
        '昼寝',
        '睡眠',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'sleep'
        ),
        'ベッド',
        '睡眠',
        0.80,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'sleep'
        ),
        '休息',
        '睡眠',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'music'
        ),
        '音楽',
        '音楽',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'music'
        ),
        '曲',
        '音楽',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'music'
        ),
        'ライブ',
        '音楽',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'music'
        ),
        '歌',
        '音楽',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'music'
        ),
        'プレイリスト',
        '音楽',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'promise'
        ),
        '約束',
        '約束',
        1.00,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'promise'
        ),
        '予定',
        '約束',
        0.85,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'promise'
        ),
        '待ち合わせ',
        '約束',
        0.90,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'promise'
        ),
        '予約',
        '約束',
        0.75,
        'exact_or_partial',
        TRUE
    ),
    (
        (
            SELECT
                id
            FROM
                group_masters
            WHERE
                group_key = 'promise'
        ),
        '締切',
        '約束',
        0.70,
        'exact_or_partial',
        TRUE
    );