// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/notifications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証中のユーザーの通知設定を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "通知設定取得",
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/dto.NotificationResponse"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "通知設定が見つからない",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証中のユーザーの通知設定と Web Push 購読情報を更新します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "通知設定更新",
                "parameters": [
                    {
                        "description": "通知設定",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateNotificationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/dto.NotificationResponse"
                        }
                    },
                    "400": {
                        "description": "リクエスト不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "通知設定が見つからない",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証中のユーザーの通知設定と Web Push 購読情報を登録します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "通知設定登録",
                "parameters": [
                    {
                        "description": "通知設定",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.NotificationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "登録成功",
                        "schema": {
                            "$ref": "#/definitions/dto.NotificationResponse"
                        }
                    },
                    "400": {
                        "description": "リクエスト不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "対象が見つからない",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pets": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証中のユーザーに紐づくペットを作成します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "ペット登録",
                "parameters": [
                    {
                        "description": "ペット情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePetRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "登録成功",
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePetResponse"
                        }
                    },
                    "400": {
                        "description": "リクエスト不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "許可されていないメソッド",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pets/departure": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "自分のアクティブペットを eligible または departed に更新します。年齢、進化段階、旅立ち予定日を満たさない更新は拒否されます。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "ペットの旅立ち状態を更新",
                "parameters": [
                    {
                        "description": "旅立ち状態",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdatePetDepartureStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/usecases.UpdatePetDepartureStatusOutput"
                        }
                    },
                    "400": {
                        "description": "条件またはリクエスト不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "アクティブペットが見つからない",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pets/evolution-status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "進化条件と進化先候補を確認します。このAPI自体は進化を実行しません。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "アクティブペットの進化可能状態を取得",
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/usecases.FindCurrentPetEvolutionStatusOutput"
                        }
                    },
                    "400": {
                        "description": "ユーザーID不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pets/evolutions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証中ユーザーの現在アクティブなペットに紐づく進化履歴を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "アクティブペットの進化履歴取得",
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/usecases.FindActivePetEvolutionHistoryOutput"
                        }
                    },
                    "400": {
                        "description": "ユーザーID不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pets/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証中のユーザーのアクティブペット、現在の群れ、旅立ち状態を取得します。departure.can_depart が true の場合は旅立ち画面を表示できます。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "現在のペットと所属群れ取得",
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/dto.CurrentPetResponse"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "アクティブペットが見つからない",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "許可されていないメソッド",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pets/me/souvenirs/latest": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証中ユーザーのアクティブペットが最後に見つけたおみやげを取得します。未取得の場合はsouvenirがnullになります。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "アクティブペットの最新おみやげ取得",
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/dto.LatestPetSouvenirResponse"
                        }
                    },
                    "400": {
                        "description": "ユーザーID不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "アクティブペットが見つからない",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/posts": {
            "post": {
                "description": "指定したペットの投稿を作成します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "投稿作成",
                "parameters": [
                    {
                        "description": "投稿内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePostRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "ペットID",
                        "name": "pet_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "作成成功",
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePostResponse"
                        }
                    },
                    "400": {
                        "description": "リクエスト不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "許可されていないメソッド",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/posts/{pet_id}": {
            "get": {
                "description": "指定したペットIDに紐づく投稿の一覧を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "ペット別投稿一覧取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ペットID",
                        "name": "pet_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/usecases.FindByPetIDPostOutput"
                            }
                        }
                    },
                    "400": {
                        "description": "ペットID不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/purchases/checkout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証中のユーザー向けにfincodeのカード登録URLを発行します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purchases"
                ],
                "summary": "買い切りカード登録開始",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.FincodeCheckoutResponse"
                        }
                    },
                    "400": {
                        "description": "リクエスト不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "購入済み",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "外部サービスエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/purchases/confirm": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "fincodeで登録済みのカードに一括決済を実行し、購入権限を有効化します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purchases"
                ],
                "summary": "買い切り決済確定",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.FincodePurchaseConfirmResponse"
                        }
                    },
                    "400": {
                        "description": "リクエスト不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "登録カードが見つかりません",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "決済サービスエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reports/{pet_id}": {
            "get": {
                "description": "指定したペットIDの指定日分レポートを取得します。date を省略した場合は前日（JST）分を返します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "日次レポート取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ペットID",
                        "name": "pet_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "取得日（YYYY-MM-DD、未指定時は前日・JST）",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/dto.ReportsResponse"
                        }
                    },
                    "400": {
                        "description": "ペットID不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/simulations/hourly": {
            "post": {
                "description": "全アクティブペットを対象に、指定時刻または現在時刻の時間単位シミュレーションを実行します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "simulations"
                ],
                "summary": "時間単位シミュレーション実行",
                "parameters": [
                    {
                        "description": "シミュレーション条件",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/controllers.RunHourlySimulationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "実行成功",
                        "schema": {
                            "$ref": "#/definitions/usecases.RunHourlyPetSimulationOutput"
                        }
                    },
                    "400": {
                        "description": "リクエストまたはマスターデータ不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "許可されていないメソッド",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/subsc/allPets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "プレミアムユーザーのuser_idに紐づく全てのペットを取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "ユーザーに紐づく全ペット取得",
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/dto.AllPetListResponse"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "サブスクリプションが必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "許可されていないメソッド",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/subsc/history_pet": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証中のユーザーに紐づく削除済みペットの一覧を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "ペット履歴取得",
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/dto.PetListResponse"
                        }
                    },
                    "400": {
                        "description": "ユーザーID不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "許可されていないメソッド",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/subsc/pet/{pet_id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "サブスクリプション契約中のユーザーが、自分のペットの名前とカラーを変更します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "ペットの名前・カラー変更",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ペットID",
                        "name": "pet_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "変更内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdatePetProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "変更成功",
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePetResponse"
                        }
                    },
                    "400": {
                        "description": "リクエスト不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "サブスクリプションが必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "ペットが見つからない",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "許可されていないメソッド",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/subsc/pets/{pet_id}/evolutions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定したペットIDに紐づく段階一覧、進化履歴、経験値集計、経験値取得イベントを取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "ペットの進化履歴取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ペットID",
                        "name": "pet_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/usecases.FindPetGrowthRecordOutput"
                        }
                    },
                    "400": {
                        "description": "ペットID不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "サブスクリプションが必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/subsc/report/{date}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "契約ユーザーの日別レポート取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "取得日。YYYY-MM-DD形式（例: 2026-08-12）",
                        "name": "date",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SubscriptionReportsResponse"
                        }
                    }
                }
            }
        },
        "/subsc/reports/{pet_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定したペットIDに紐づく全レポートを日時の新しい順で取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "ペットの全レポート取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ペットID",
                        "name": "pet_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/usecases.FindByTodayReportOutput"
                            }
                        }
                    },
                    "400": {
                        "description": "ペットID不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "サブスクリプションが必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/subscriptions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証中のユーザーのサブスクリプション契約状態を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "サブスクリプション状態取得",
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/dto.FincodeSubscriptionStatusResponse"
                        }
                    },
                    "400": {
                        "description": "リクエスト不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "契約情報が見つからない",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "契約状態が競合",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "外部サービスエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証中のユーザーのサブスクリプションを解約します。",
                "tags": [
                    "subscriptions"
                ],
                "summary": "サブスクリプション解約",
                "responses": {
                    "202": {
                        "description": "解約リクエスト受理"
                    },
                    "400": {
                        "description": "リクエスト不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "契約情報が見つからない",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "契約状態が競合",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "外部サービスエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/subscriptions/checkout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証中のユーザー向けに fincode の決済ページを作成します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "サブスクリプション決済開始",
                "responses": {
                    "201": {
                        "description": "決済ページ作成成功",
                        "schema": {
                            "$ref": "#/definitions/dto.FincodeCheckoutResponse"
                        }
                    },
                    "400": {
                        "description": "リクエスト不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "ユーザーが見つからない",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "すでに契約済み",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "外部サービスエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "メールアドレスとパスワードを使用して新規ユーザーを作成し、認証トークンを返します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "ユーザー登録",
                "parameters": [
                    {
                        "description": "ユーザー情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "登録成功",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "リクエスト不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "許可されていないメソッド",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/email": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "メールアドレス変更",
                "parameters": [
                    {
                        "description": "変更内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserResponse"
                        }
                    },
                    "400": {
                        "description": "入力不備",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証失敗",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "メールアドレス重複",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "メールアドレスとパスワード、または Authorization ヘッダーのトークンを使用して認証します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "ログイン",
                "parameters": [
                    {
                        "description": "ログイン情報（トークン認証時は省略可能）",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Bearer トークン",
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ログイン成功",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "認証情報不足またはリクエスト不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証失敗",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "許可されていないメソッド",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/me/souvenir-praise/{date}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "二回以降も成功し、初回の選択時刻を保持します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "おみやげの「ほめる」選択済み記録",
                "parameters": [
                    {
                        "type": "string",
                        "description": "レポート対象日。YYYY-MM-DD形式",
                        "name": "date",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SouvenirPraiseFlagResponse"
                        }
                    },
                    "400": {
                        "description": "日付またはユーザーID不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証が必要",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/password": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "パスワード変更",
                "parameters": [
                    {
                        "description": "変更内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserResponse"
                        }
                    },
                    "400": {
                        "description": "入力不備",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "認証失敗",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/webhooks/fincode": {
            "post": {
                "description": "fincode から送信されるカード登録・契約登録・契約解約イベントを処理します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "fincode Webhook受信",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Webhook署名",
                        "name": "Fincode-Signature",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Webhookイベント",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.WebhookEvent"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "受信成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "ペイロード不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "署名不正",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "許可されていないメソッド",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "処理失敗",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.RunHourlySimulationRequest": {
            "type": "object",
            "properties": {
                "simulated_at": {
                    "type": "string"
                }
            }
        },
        "controllers.WebhookEvent": {
            "type": "object",
            "properties": {
                "card_id": {
                    "type": "string"
                },
                "card_status": {
                    "type": "string"
                },
                "customer_id": {
                    "type": "string"
                },
                "event": {
                    "type": "string"
                },
                "pay_type": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "subscription_id": {
                    "type": "string"
                }
            }
        },
        "dto.AllPetListResponse": {
            "type": "object",
            "properties": {
                "pets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AllPetResponse"
                    }
                }
            }
        },
        "dto.AllPetResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                }
            }
        },
        "dto.CreatePetRequest": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.CreatePetResponse": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "curiosity": {
                    "type": "number"
                },
                "current_group_master_id": {
                    "type": "integer"
                },
                "current_stage_id": {
                    "type": "integer"
                },
                "energy": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "is_deleted": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "routine": {
                    "type": "number"
                },
                "sociality": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.CreatePostRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "dto.CreatePostResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "content_embedding": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                }
            }
        },
        "dto.CreateUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.CreateUserResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "fincode_customer_id": {
                    "type": "string"
                },
                "fincode_subscription_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "subsc": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.CurrentGroupResponse": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "group_key": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "dto.CurrentPetResponse": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "current_group": {
                    "$ref": "#/definitions/dto.CurrentGroupResponse"
                },
                "current_stage_id": {
                    "type": "integer"
                },
                "departure": {
                    "$ref": "#/definitions/dto.DepartureResponse"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.DepartureResponse": {
            "type": "object",
            "properties": {
                "can_depart": {
                    "type": "boolean"
                },
                "eligible_at": {
                    "type": "string"
                },
                "scheduled_departure_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.FincodeCheckoutResponse": {
            "type": "object",
            "properties": {
                "checkout_url": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                }
            }
        },
        "dto.FincodePurchaseConfirmResponse": {
            "type": "object",
            "properties": {
                "subsc": {
                    "type": "boolean"
                }
            }
        },
        "dto.FincodeSubscriptionStatusResponse": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "fincode_customer_id": {
                    "type": "string"
                },
                "fincode_subscription_id": {
                    "type": "string"
                }
            }
        },
        "dto.LatestPetSouvenirItemResponse": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "foundAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imageURL": {
                    "type": "string"
                },
                "reported": {
                    "type": "boolean"
                }
            }
        },
        "dto.LatestPetSouvenirResponse": {
            "type": "object",
            "properties": {
                "souvenir": {
                    "$ref": "#/definitions/dto.LatestPetSouvenirItemResponse"
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dto.UserResponse"
                }
            }
        },
        "dto.NotificationRequest": {
            "type": "object",
            "properties": {
                "is_all_enabled": {
                    "type": "boolean"
                },
                "is_message_enabled": {
                    "type": "boolean"
                },
                "is_report_enabled": {
                    "type": "boolean"
                },
                "is_yoyo_enabled": {
                    "type": "boolean"
                },
                "subscription": {
                    "type": "object"
                }
            }
        },
        "dto.NotificationResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "is_all_enabled": {
                    "type": "boolean"
                },
                "is_message_enabled": {
                    "type": "boolean"
                },
                "is_report_enabled": {
                    "type": "boolean"
                },
                "is_yoyo_enabled": {
                    "type": "boolean"
                },
                "subscription": {
                    "type": "object"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.PetListResponse": {
            "type": "object",
            "properties": {
                "pets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PetResponse"
                    }
                }
            }
        },
        "dto.PetResponse": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "curiosity": {
                    "type": "number"
                },
                "current_group_master_id": {
                    "type": "integer"
                },
                "current_stage_id": {
                    "type": "integer"
                },
                "energy": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "is_deleted": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "routine": {
                    "type": "number"
                },
                "sociality": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.ReportResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "gossip": {
                    "type": "string"
                },
                "groupName": {
                    "type": "string"
                },
                "hourSlot": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "petID": {
                    "type": "string"
                },
                "rumors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "souvenirs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.SouvenirResponse"
                    }
                }
            }
        },
        "dto.ReportsResponse": {
            "type": "object",
            "properties": {
                "hasPraised": {
                    "type": "boolean"
                },
                "reports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ReportResponse"
                    }
                }
            }
        },
        "dto.SouvenirPraiseFlagResponse": {
            "type": "object",
            "properties": {
                "hasPraised": {
                    "type": "boolean"
                },
                "praisedAt": {
                    "type": "string"
                },
                "reportDate": {
                    "type": "string"
                }
            }
        },
        "dto.SouvenirResponse": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imageURL": {
                    "type": "string"
                }
            }
        },
        "dto.SubscriptionReportPet": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "current_stage_key": {
                    "type": "string"
                },
                "current_stage_no": {
                    "type": "integer"
                },
                "is_deleted": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                }
            }
        },
        "dto.SubscriptionReportsResponse": {
            "type": "object",
            "properties": {
                "hasPraised": {
                    "type": "boolean"
                },
                "pet": {
                    "$ref": "#/definitions/dto.SubscriptionReportPet"
                },
                "reports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ReportResponse"
                    }
                }
            }
        },
        "dto.UpdateNotificationRequest": {
            "type": "object",
            "properties": {
                "is_all_enabled": {
                    "type": "boolean"
                },
                "is_message_enabled": {
                    "type": "boolean"
                },
                "is_report_enabled": {
                    "type": "boolean"
                },
                "is_yoyo_enabled": {
                    "type": "boolean"
                },
                "subscription": {
                    "type": "object"
                }
            }
        },
        "dto.UpdatePetDepartureStatusRequest": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.UpdatePetProfileRequest": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateUserEmailRequest": {
            "type": "object",
            "properties": {
                "current_email": {
                    "type": "string"
                },
                "current_password": {
                    "type": "string"
                },
                "new_email": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateUserPasswordRequest": {
            "type": "object",
            "properties": {
                "current_password": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateUserResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.UserResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fincode_customer_id": {
                    "type": "string"
                },
                "fincode_subscription_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "subsc": {
                    "type": "boolean"
                }
            }
        },
        "usecases.ActivePetEvolutionStageOutput": {
            "type": "object",
            "properties": {
                "branch_key": {
                    "type": "string"
                },
                "current": {
                    "type": "boolean"
                },
                "evolved_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "stage_key": {
                    "type": "string"
                },
                "stage_no": {
                    "type": "integer"
                },
                "unlocked": {
                    "type": "boolean"
                }
            }
        },
        "usecases.CurrentPetEvolutionCandidateOutput": {
            "type": "object",
            "properties": {
                "ready": {
                    "type": "boolean"
                },
                "requirements": {
                    "$ref": "#/definitions/usecases.CurrentPetEvolutionRequirements"
                },
                "rule_id": {
                    "type": "integer"
                },
                "selected_for_pet": {
                    "type": "boolean"
                },
                "to_stage": {
                    "$ref": "#/definitions/usecases.CurrentPetEvolutionStageOutput"
                }
            }
        },
        "usecases.CurrentPetEvolutionProgress": {
            "type": "object",
            "properties": {
                "current": {
                    "type": "integer"
                },
                "met": {
                    "type": "boolean"
                },
                "remaining": {
                    "type": "integer"
                },
                "required": {
                    "type": "integer"
                }
            }
        },
        "usecases.CurrentPetEvolutionRequirements": {
            "type": "object",
            "properties": {
                "days_since_last_evolution": {
                    "$ref": "#/definitions/usecases.CurrentPetEvolutionProgress"
                },
                "experience": {
                    "$ref": "#/definitions/usecases.CurrentPetEvolutionProgress"
                },
                "feed_count": {
                    "$ref": "#/definitions/usecases.CurrentPetEvolutionProgress"
                }
            }
        },
        "usecases.CurrentPetEvolutionStageOutput": {
            "type": "object",
            "properties": {
                "branch_key": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "stage_key": {
                    "type": "string"
                },
                "stage_no": {
                    "type": "integer"
                }
            }
        },
        "usecases.FindActivePetEvolutionHistoryOutput": {
            "type": "object",
            "properties": {
                "current_stage_id": {
                    "type": "integer"
                },
                "evolutions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/usecases.PetGrowthEvolutionOutput"
                    }
                },
                "pet_id": {
                    "type": "string"
                },
                "stages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/usecases.ActivePetEvolutionStageOutput"
                    }
                }
            }
        },
        "usecases.FindByPetIDPostOutput": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "contentEmbedding": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "petID": {
                    "type": "string"
                }
            }
        },
        "usecases.FindByTodayReportOutput": {
            "type": "object",
            "properties": {
                "Group_name": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "gossip": {
                    "type": "string"
                },
                "hourSlot": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "petID": {
                    "type": "string"
                },
                "rumors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "usecases.FindCurrentPetEvolutionStatusOutput": {
            "type": "object",
            "properties": {
                "can_evolve": {
                    "type": "boolean"
                },
                "current_stage": {
                    "$ref": "#/definitions/usecases.CurrentPetEvolutionStageOutput"
                },
                "next_stages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/usecases.CurrentPetEvolutionCandidateOutput"
                    }
                },
                "pet_id": {
                    "type": "string"
                }
            }
        },
        "usecases.FindPetGrowthRecordOutput": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "current_stage_id": {
                    "type": "integer"
                },
                "evolutions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/usecases.PetGrowthEvolutionOutput"
                    }
                },
                "experience_events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/usecases.PetGrowthExperienceEventOutput"
                    }
                },
                "feed_count": {
                    "type": "integer"
                },
                "pet_id": {
                    "type": "string"
                },
                "stages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/usecases.ActivePetEvolutionStageOutput"
                    }
                },
                "total_experience": {
                    "type": "integer"
                }
            }
        },
        "usecases.PetGrowthEvolutionOutput": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "evolution_rule_id": {
                    "type": "integer"
                },
                "evolved_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "primary_status": {
                    "type": "string"
                },
                "stage_id": {
                    "type": "integer"
                }
            }
        },
        "usecases.PetGrowthExperienceEventOutput": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "capped_amount": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "experience_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "source_id": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                }
            }
        },
        "usecases.RunHourlyPetSimulationOutput": {
            "type": "object",
            "properties": {
                "interest_propagations": {
                    "type": "integer"
                },
                "processed": {
                    "type": "integer"
                },
                "reports_created": {
                    "type": "integer"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/usecases.RunHourlyPetSimulationPetResult"
                    }
                },
                "simulated_at": {
                    "type": "string"
                },
                "skipped": {
                    "type": "integer"
                },
                "total_pets": {
                    "type": "integer"
                }
            }
        },
        "usecases.RunHourlyPetSimulationPetResult": {
            "type": "object",
            "properties": {
                "ambient_event": {
                    "type": "string"
                },
                "move_probability": {
                    "type": "number"
                },
                "moved": {
                    "type": "boolean"
                },
                "next_group_master_id": {
                    "type": "integer"
                },
                "pet_id": {
                    "type": "string"
                },
                "previous_group_master_id": {
                    "type": "integer"
                }
            }
        },
        "usecases.UpdatePetDepartureStatusOutput": {
            "type": "object",
            "properties": {
                "departed_at": {
                    "type": "string"
                },
                "eligible_at": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                },
                "scheduled_departure_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "「Bearer {JWT}」の形式で入力してください",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "PETYO-YO API",
	Description:      "PETYO-YO backend API documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
